import type { AvailableLanguages } from '$lib/Project.svelte'
import { isShippedRuntimeAbi } from '$lib/runtimeAbi'

/** One public function of the Runtime library, as its header declares and documents it. */
export type RuntimeFunction = {
    name: string
    /** The header that declares it, such as `stdio.h`. */
    header: string
    /** The declaration, such as `int printf(const char *format, ...)`. */
    prototype: string
    /** The one-line documentation comment above the declaration. */
    doc: string
}

/**
 * The public functions of one Runtime ABI, the same for every Target because they come from the
 * headers. Small, so live checking can explain an undefined `printf` and completion can offer the
 * library without downloading any member.
 */
export type RuntimeFunctionList = {
    abi: string
    functions: RuntimeFunction[]
}

/** Where a Library member's assembly lines came from in the library's C source. */
export type RuntimeMemberSource = {
    /** The C source path inside the library, such as `src/stdio/printf.c`. */
    source: string
    /** Zero-based C line for each zero-based assembly line, or null where nothing maps. */
    lines: (number | null)[]
}

/**
 * The implementation of one Runtime ABI for one Target: Library members (GNU compiler assembly),
 * the index naming the member that defines each global, the documented public functions and the
 * C origin of each member's lines. Generated by `scripts/runtime/build.mjs`.
 */
export type RuntimeLibraryData = {
    abi: string
    target: string
    /** The compiler that produced the members, for the record. */
    compiler: string
    members: Record<string, string>
    index: Record<string, string>
    /** Globals the library supplies even to a weak reference, which otherwise pulls no member. */
    resolveWeak?: string[]
    memberSources: Record<string, RuntimeMemberSource>
}

type Loader = () => Promise<{ default: unknown }>

//Lazily imported, so a Project that never links the library never downloads it; the bundler gives
//each one a chunk of its own, and the language Worker imports the same chunks.
const LOADERS: Record<string, Loader> = {
    'v1:RISC-V': () => import('./generated/v1/riscv32.json'),
    'v1:RISC-V-64': () => import('./generated/v1/riscv64.json'),
    'v1:MIPS': () => import('./generated/v1/mips.json')
}

const FUNCTION_LOADERS: Record<string, Loader> = {
    v1: () => import('./generated/v1/functions.json')
}

//The library's headers, uploaded with every compilation as the program's only system headers.
const HEADER_LOADERS: Record<string, Loader> = {
    v1: () => import('./generated/v1/include.json')
}

//The library's C sources, read when a Library member's origin is opened.
const SOURCE_LOADERS: Record<string, Loader> = {
    v1: () => import('./generated/v1/sources.json')
}

const loaded = new Map<string, RuntimeLibraryData>()
const loading = new Map<string, Promise<RuntimeLibraryData>>()
const loadedFunctions = new Map<string, RuntimeFunctionList>()

function key(abi: string, language: AvailableLanguages) {
    return `${abi}:${language}`
}

/** Whether this editor ships the library a Build of this Target with this ABI would link. */
export function hasRuntimeLibraryFor(abi: string, language: AvailableLanguages): boolean {
    return (
        isShippedRuntimeAbi(abi) &&
        Object.prototype.hasOwnProperty.call(LOADERS, key(abi, language))
    )
}

/** Loads (once) the library for an ABI and Target. */
export function loadRuntimeLibrary(
    abi: string,
    language: AvailableLanguages
): Promise<RuntimeLibraryData> {
    const id = key(abi, language)
    const ready = loaded.get(id)
    if (ready) return Promise.resolve(ready)
    let pending = loading.get(id)
    if (!pending) {
        const loader = LOADERS[id]
        if (!loader)
            return Promise.reject(new Error(`There is no Runtime library ${abi} for ${language}`))
        pending = loader()
            .then((module) => {
                const data = module.default as RuntimeLibraryData
                loaded.set(id, data)
                return data
            })
            .finally(() => loading.delete(id))
        loading.set(id, pending)
    }
    return pending
}

/**
 * Supplies a library without importing it, as if it had been loaded: what tests use to link a small
 * library of their own, and what a library built in the browser would use.
 */
export function provideRuntimeLibrary(
    abi: string,
    language: AvailableLanguages,
    data: RuntimeLibraryData
): void {
    loaded.set(key(abi, language), data)
}

/** Supplies the public function list of an ABI without importing it; see `provideRuntimeLibrary`. */
export function provideRuntimeFunctions(list: RuntimeFunctionList): void {
    loadedFunctions.set(list.abi, list)
}

/** The library when it has already been loaded, for synchronous callers that loaded it first. */
export function loadedRuntimeLibrary(
    abi: string,
    language: AvailableLanguages
): RuntimeLibraryData | undefined {
    return loaded.get(key(abi, language))
}

/** Loads (once) the public functions of an ABI. */
export async function loadRuntimeFunctions(abi: string): Promise<RuntimeFunctionList | undefined> {
    const ready = loadedFunctions.get(abi)
    if (ready) return ready
    const loader = FUNCTION_LOADERS[abi]
    if (!loader) return undefined
    const list = (await loader()).default as RuntimeFunctionList
    loadedFunctions.set(abi, list)
    return list
}

export function loadedRuntimeFunctions(abi: string): RuntimeFunctionList | undefined {
    return loadedFunctions.get(abi)
}

/** The headers of an ABI, keyed by their path under the include directory (`stdio.h`, `sys/x.h`). */
export async function loadRuntimeHeaders(abi: string): Promise<Record<string, string>> {
    const loader = HEADER_LOADERS[abi]
    if (!loader) throw new Error(`There are no Runtime library headers for ${abi}`)
    return (await loader()).default as Record<string, string>
}

const loadedSources = new Map<string, Record<string, string>>()

/** The C sources of an ABI's library, keyed by their path inside the library (`src/stdio/printf.c`). */
export async function loadRuntimeSources(abi: string): Promise<Record<string, string>> {
    const ready = loadedSources.get(abi)
    if (ready) return ready
    const loader = SOURCE_LOADERS[abi]
    if (!loader) return {}
    const sources = (await loader()).default as Record<string, string>
    loadedSources.set(abi, sources)
    return sources
}

export function loadedRuntimeSources(abi: string): Record<string, string> | undefined {
    return loadedSources.get(abi)
}

/** Where the editor shows one of the library's C sources: `@runtime/v1/src/stdio/printf.c`. */
export function runtimeSourcePath(abi: string, source: string): string {
    return `@runtime/${abi}/${source}`
}

/** The ABI and library-relative path of a C source shown under `@runtime/`, or undefined. */
export function parseRuntimeSourcePath(path: string): { abi: string; source: string } | undefined {
    const match = /^@runtime\/(v\d+)\/(src\/.+)$/.exec(path)
    return match ? { abi: match[1], source: match[2] } : undefined
}

/** What the Core links: members and index. */
export function coreLibrary(data: RuntimeLibraryData) {
    return { members: data.members, index: data.index, resolveWeak: data.resolveWeak ?? [] }
}

const UNRESOLVED = [/^Unresolved symbol: (\S+)$/, /^Symbol "([^"]+)" not found in symbol table\.?$/]

/** The name an "undefined symbol" Diagnostic is about, or undefined for any other message. */
export function unresolvedSymbol(message: string): string | undefined {
    for (const pattern of UNRESOLVED) {
        const match = pattern.exec(message.trim())
        if (match) return match[1]
    }
    return undefined
}

/**
 * The Hint for an undefined symbol the Runtime library defines, when the Build does not link it:
 * hand-written assembly has the library off by default, so a call to `printf` explains how to
 * turn it on instead of only saying the symbol does not exist.
 */
export function runtimeLibraryHint(
    message: string,
    list: RuntimeFunctionList | undefined
): string | undefined {
    const name = unresolvedSymbol(message)
    if (!name || !list?.functions.some((entry) => entry.name === name)) return undefined
    return `${name} is in the Runtime library. Turn on "Link Runtime library" in the Project Settings to use it.`
}
